### ISSUE TITLE
修改 byzer  build 产出的问题

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-build#32]
1. download 站 misc 中内容散乱，且不知道对应的东西是干什么用的 
![image](https://user-images.githubusercontent.com/11333496/160074781-a22bd1f5-7f54-45b5-aee5-246fe529ac17.png)

- 这里如果是 common lib jar，每个部署都需要的，比如 nlp-lang.jar, ansj-seg.jar, 请考虑直接打入到 byzer-lang 引擎的默认依赖里
- JDK 单独设置一个 folder
- 环境独立的jar，path 请做如下区分
```
|-- cloud
    |-- aws
    |-- azure
    |-- alicloud
    |-- qcloud
|-- hadoop
    |-- apache_hadoop
    |-- hdp
    |-- cdh
|-- jdk
    |-- jdk8
    |-- jdk14
|-- byzer-cli
    |-- byzer-cli-darwin-amd64
    |-- byzer-cli-linux-amd64
    |-- byzer-cli-windows-amd64.exe
```

2. Byzer build 中需要修改需要手动 copy jar 的逻辑，策略由**先检查本地是否缓存了这些依赖，如果 没有就自动去 download 站点** 进行拉取，避免 byzer-build 只能在部分环境上能跑起来

3. byzer-build 中修复所有naming 相关的问题，将 mlsql 和 kolo 全部统一为 byzer，对应的 repo 中也需要有修改

4. README 中加入开发机如何使用 byzer-build 进行打包的说明

**Comment by ZhengshuaiPENG** [comment]
关联issue： https://github.com/byzer-org/byzer-lang/issues/1678

**Comment by ZhengshuaiPENG** [comment]
estimate  5d

**Comment by hellozepp** [comment]
https://github.com/byzer-org/byzer-lang/issues/1752
