### ISSUE TITLE
发行的各个版本的包名不统一，需要统一规范

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-build#33]
在 Download 站点上，目前的命名如下
![image](https://user-images.githubusercontent.com/11333496/160227008-1a89f476-0e73-47c6-9575-f7a54dcb6964.png)

而在 docker hub 上，产出的 tag 如下
![image](https://user-images.githubusercontent.com/11333496/160227044-fa364794-4674-48c2-aa68-a6a03a1fad1b.png)

问题如下：
1. 包名和 docker hub 的tag不一致，这里需要保持一致的规范 `{spark-version}-{byzer-version}`
2. “命令行版本” 应该对应的是 byzer-sandbox，“二进制版本” 对应的是 byzer-lang，生成的包名需要进行区分，这里提出一个 proposal， 如下：

|  命名   | 原命名  |二进制包名   | docker hub  |
|  ----  | ----  |  ----  | ----  |
|Byzer All In One |Byzer 命令行版本|byzer-lang-all-in-one-{OS}-{SparkVersion}-{ByzerVersion}.tar.gz|byzer-sandbox|
|Byzer Server|Byzer 二进制版本|byzer-lang-{SparkVersion}-{ByzerVersion}.tar.gz|byzer-lang |

3. Byzer Desktop 版本， 统一命名规范为 `byzer-vscode-extension-{OS}-{version}.vsix`

**Comment by ZhengshuaiPENG** [comment]
关联issue： https://github.com/byzer-org/task-management/issues/16

**Comment by ZhengshuaiPENG** [comment]
estimate date 5 day

**Comment by hellozepp** [comment]
jar包名修改为： byzer-lang-3.1.1-2.12-2.3.0-SNAPSHOT.jar
