### ISSUE TITLE
K8S 内部镜像在 pod 启动后，没有产生任何日志

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-build#46]
在 byzer 的 k8s 镜像启动后，进入 pod 后没有任何的日志可以查看，需要考虑使用一个机制来保证 k8s 环境中，日志是正常可用的，且需要考虑自动备份和清理机制，避免日志把 pod 的磁盘打爆了

**Comment by ZhengshuaiPENG** [comment]
yaml（byzer-k8s） 的方式 和 helm chart 的方式，都需要能够产生日志

1d

**Comment by chncaesar** [comment]
Fixed. see configMap & deployment yaml in https://github.com/byzer-org/byzer-cicd/tree/master/Flag/byzer-lang
