### ISSUE TITLE
byzer-lang-k8s 3.1.1-latest 镜像中程序包名版本有误

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-build#49]
byzer-lang-k8s 3.1.1-latest 镜像中，启动命令的 jar 包版本号有误，目前是 `streamingpro-mlsql-spark_3.0_2.12-2.2.2.jar` 

应该等 naming 更新成 `byzer-engine.jar` 后, 此问题应该被fix，留此问题进行校验

**Comment by hellozepp** [comment]
@ZhengshuaiPENG 方案修改为如下：
启动命令的 jar 名称统一修改为 `byzer-lang-<spark版本>-<scala版本>-<byzer版本>.jar`
e.g. : byzer-lang-3.1.1-2.12-2.2.2.jar

**Comment by ZhengshuaiPENG** [comment]
byzer lang 的启动脚本`byzer.sh` 会将该版本号隐藏在背后，故此issue关闭
