### ISSUE TITLE
默认删除 byzer-lang 产品包以及 镜像中的 velocity jar 

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-build#51]
目前发现 `${SPARK_HOME} /jars/velocity-1.5.jar` 和 byzer engine 中的 velocity-1.5.jar 有冲突，会导致解析 json path 的时候出错，比如 `get_json_object(json_string, path)` 函数就无法取到正确的值。

需要将：
1. Byzer all in one  tar包
2. Byzer vs code extension 中自带的 byzer engine 
3. byzer-lang-sandbox 以及 byzer-lang-k8s 等镜像中，默认删除此 jar

**Comment by chncaesar** [comment]
[x] k8s image changed and test
[ ] byzer cli
[ ] vs code plugin
[ ] byzer-lang docker compose image

**Comment by chncaesar** [comment]
PR #53
